name: Build and Archive Python Package

on:
  push:
    branches:
      - main  # Esegui il workflow solo quando c'è un push sulla branch principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurazione di Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Puoi cambiare la versione di Python

      # Installazione delle dipendenze necessarie per costruire il pacchetto
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      # Costruzione del pacchetto
      - name: Build the package
        run: python setup.py sdist bdist_wheel

      # Salvare l'output come artefatto
      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: kseniaWebsocketLibrary
          path: dist/
